export const projects = [
    {
        id: "mary-river",
        title: "Mary River Station",
        subtitle: "Take time and stay a while.",
        image: "/images/mary-river.jpg",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "steve-booker",
        title: "Steve Booker",
        subtitle: "Branding a social media giant.",
        image: "/images/steve-booker.jpg",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "zoomo",
        title: "Zoomo",
        subtitle: "Take time and stay a while.",
        image: "/images/zoomo.png",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "the-203",
        title: "The 203",
        subtitle: "Take time and stay a while.",
        image: "/images/the-203.jpg",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "valley-velo",
        title: "Valley Velo",
        subtitle: "Take time and stay a while.",
        image: "/images/valley-velo.jpg",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "rain-harvesting",
        title: "Rain Harvesting",
        subtitle: "Take time and stay a while.",
        image: "/images/rain-harvesting-logo.svg",
        video: "/videos/rain-harvesting-video.mp4",
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "link-kit",
        title: "Link Kit",
        subtitle: "Take time and stay a while.",
        image: "/images/link-kit.svg",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "apollo",
        title: "Apollo",
        subtitle: "Take time and stay a while.",
        image: "/images/apollo.png",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
    {
        id: "urban-play",
        title: "Urban Play",
        subtitle: "Take time and stay a while.",
        image: "/images/urban-play.png",
        video: null,
        badge: "Completed at Groundcrew",
        status: "Coming Soon",
    },
]
